# Generated by Django 3.0.2 on 2020-02-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='dead_line',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
