# Generated by Django 3.0.2 on 2020-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_auto_20200202_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
