# Generated by Django 3.0.2 on 2020-02-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_auto_20200216_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Rejected'), (3, 'Promised'), (4, 'Failed'), (5, 'Completed'), (6, 'Rewarded')]),
        ),
    ]
