# Generated by Django 3.0.2 on 2020-02-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_auto_20200202_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promise',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='promise',
            old_name='promised_date',
            new_name='promise_date',
        ),
        migrations.RenameField(
            model_name='promise',
            old_name='image',
            new_name='reward_image',
        ),
        migrations.AddField(
            model_name='person',
            name='family_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='mail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='family_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='performer_person_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='reward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='reward_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='rewarder_person_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
