# Generated by Django 3.0.2 on 2020-02-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_auto_20200216_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
