# Generated by Django 3.0.2 on 2020-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0004_auto_20200202_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='reward_image',
        ),
    ]
